Repository matthewhartstonge/storage, pull requests merged in 2023-07, with the labels that each got.

#72 :arrow_up: Add MFA factors to user record
  user.go
  user_test.go
Labels: size/M

#73 :arrow_up: deps: updates dependencies.
  .github/workflows/go.yaml
  examples/mongo/go.mod
  examples/mongo/go.sum
  examples/mongo/main.go
  examples/mongo/resourceserver/resource.go
  go.mod
  go.sum
Labels: size/XXL

#74 :ship: v0.32.0 - 2023-07-18
  CHANGELOG.md
  LICENSE
  NOTICE
  README.md
Labels: size/S
